import type { BusinessPolicy } from './types';

export const CURRENT_NEM_POLICY_VERSION = 'salvage-bridge-default-2026-05-31';

export const DEFAULT_BUSINESS_POLICY: BusinessPolicy = {
  version: CURRENT_NEM_POLICY_VERSION,
  updatedAt: '2026-05-23T00:00:00.000Z',
  branding: {
    brandName: 'Salvage Bridge',
    legalName: 'Salvage Bridge Technologies',
    supportEmail: 'support@salvagebridge.com',
    primaryColor: '#0C0C0B',
    accentColor: '#D97706',
    logoPath: '/icons/icon-512.png',
    faviconPath: '/icons/icon-192.png',
    homepageMode: 'landing',
    homepageTemplate: 'reclaim_editorial',
    homepageTheme: 'night',
    splashEnabled: true,
    homepageCopy: {
      heroTitle: 'Where total losses become recovered capital.',
      heroSubtitle: 'A salvage auction platform for insurers, adjusters, vendors, and finance teams.',
      supportingText: 'Verified vendors. Real-time auctions. Branded documents. Auditable recovery workflows.',
      primaryCtaLabel: 'Start recovery',
      secondaryCtaLabel: 'Sign in',
      eyebrow: 'Salvage auction platform for insurance',
      trustLine: 'Built for controlled recovery, verified buyers, and clearer settlement.',
      statOneLabel: 'Average recovery rate',
      statOneValue: '94%',
      statTwoLabel: 'Average time to sale',
      statTwoValue: '48hrs',
      statThreeLabel: 'Verified buyers',
      statThreeValue: '3,200+',
      authHeadline: 'Recover value without losing control.',
      authSubtitle: 'Sign in to manage salvage cases, approvals, auctions, payments, and compliance evidence.',
      workflowTitle: 'Recovery workflow',
      workflowSubtitle: 'A controlled journey from claim intake to settlement.',
      workflowStepOneTitle: 'Intake',
      workflowStepOneBody: 'Capture claim assets, documents, photos, notes, and inspection details.',
      workflowStepTwoTitle: 'Review',
      workflowStepTwoBody: 'Route approval, valuation, KYC, and risk signals through controlled workflows.',
      workflowStepThreeTitle: 'Auction',
      workflowStepThreeBody: 'Run verified bidding with deposits, extensions, notifications, and audit trails.',
      workflowStepFourTitle: 'Settle',
      workflowStepFourBody: 'Generate branded documents, collect payment, and reconcile recovered value.',
      auctionSectionEyebrow: 'Live now',
      auctionSectionTitle: 'Auction-ready inventory',
      auctionSectionButtonLabel: 'Open workspace',
      operationsSectionEyebrow: 'Control stack',
      operationsSectionTitle: 'Recovery rules on one board.',
      operationsSectionSubtitle: 'A clear operating view for claims, auctions, payments, documents, and review teams.',
      operationsCardOneTitle: 'Vendor access',
      operationsCardOneBody: 'Verification, registration fees, KYC tier, and bid limits keep vendor access controlled.',
      operationsCardTwoTitle: 'Auction rules',
      operationsCardTwoBody: 'Reserve rules, extensions, document windows, and deadlines stay clear.',
      operationsCardThreeTitle: 'Payment steps',
      operationsCardThreeBody: 'Wallet, deposit, and settlement steps help finance teams close each recovery.',
      proofSectionTitle: 'Controlled salvage recovery from intake to settlement.',
      proofSectionSubtitle: 'Configure vendor onboarding, auctions, documents, notifications, and public pages from one place.',
      proofCardOneTitle: 'Verified vendor access',
      proofCardOneBody: 'KYC, registration fees, bid limits, and manual review keep access controlled.',
      proofCardTwoTitle: 'Auditable auction flow',
      proofCardTwoBody: 'Reserve rules, extensions, documents, payment deadlines, and fraud gates are traceable.',
      proofCardThreeTitle: 'Branded documents',
      proofCardThreeBody: 'Letterheads, legal names, support contacts, waivers, receipts, and reports stay consistent.',
      proofCardFourTitle: 'Operational support',
      proofCardFourBody: 'Email, SMS, push, contact forms, and reminders use the active brand details.',
      proofContactLabel: 'Contact',
      recoveryBriefTitle: 'One clear path from claim intake to signed handover.',
      recoveryBriefBody: 'A premium recovery journey with trust markers, auction inventory, and contact points.',
      contactHeadline: 'Get in touch',
      contactSubtitle: 'Have questions? We would love to hear from you.',
    },
  },
  auth: {
    emailPasswordEnabled: true,
    googleOAuthEnabled: false,
    businessEmailOnly: false,
    allowedEmailDomains: [],
    staffMfaRequired: false,
    vendorMfaRequired: false,
    userManagedMfaAllowed: true,
  },
  onboarding: {
    mode: 'tiered_bvn_fee_tier2',
    tier1BidLimit: 500_000,
    registrationFeeRequired: true,
    registrationFeeAmount: 12_500,
    registrationFeeDueDays: 7,
    allowBrowseBeforeKyc: false,
    allowBidAfterTier1: true,
    requireTier2ForUnlimitedBidding: true,
    finalTier2Decision: 'manual_review',
  },
  kyc: {
    provider: 'dojah',
    tier1RequiresBvn: true,
    tier2RequiresBusinessData: true,
    tier2RequiresGovernmentId: true,
    tier2RequiresLiveness: true,
    tier2RequiresAddress: true,
    tier2RequiresAmlScreening: true,
    tier2RequiresDuplicateIdentityCheck: true,
    providerPassRequiresInternalReview: true,
  },
  payments: {
    defaultProvider: 'paystack',
    registrationFeeProvider: 'paystack',
    auctionPaymentProvider: 'paystack',
    walletEnabled: true,
    paystackEnabled: true,
    flutterwaveEnabled: false,
    hybridPaymentEnabled: true,
    manualPaymentEnabled: false,
    paymentDeadlineAfterSigningHours: 72,
  },
  escrow: {
    depositSystemEnabled: true,
    depositRatePercent: 10,
    minimumDepositFloor: 100_000,
    topBiddersToKeepFrozen: 3,
    forfeiturePercentage: 100,
  },
  auctions: {
    minimumBidIncrement: 20_000,
    documentValidityHours: 48,
    maxGraceExtensions: 2,
    graceExtensionDurationHours: 24,
    fallbackBufferHours: 24,
    reserveValueStrategy: 'percentage_of_salvage_value',
    reserveValuePercentage: 70,
    socketMode: 'polling_primary_socket_secondary',
  },
  cases: {
    enabledAssetTypes: {
      vehicle: {
        enabled: true,
        label: 'Vehicle',
        promptProfile: 'vehicle',
        requiredFields: ['vehicleMake', 'vehicleModel', 'vehicleYear'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      machinery: {
        enabled: true,
        label: 'Machinery & Equipment',
        promptProfile: 'machinery',
        requiredFields: ['machineryBrand', 'machineryType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      property: {
        enabled: true,
        label: 'Building / Fixtures',
        promptProfile: 'property',
        requiredFields: ['propertyType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      electronics: {
        enabled: true,
        label: 'Electronics',
        promptProfile: 'electronics',
        requiredFields: ['electronicsBrand', 'electronicsModel'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      jewelry: {
        enabled: false,
        label: 'Jewelry & Watches',
        promptProfile: 'jewelry',
        requiredFields: ['jewelryType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      appliance: {
        enabled: false,
        label: 'Appliance',
        promptProfile: 'electronics',
        requiredFields: ['applianceBrand', 'applianceModel'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      furniture: {
        enabled: true,
        label: 'Furniture',
        promptProfile: 'general_asset',
        requiredFields: ['furnitureType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      stock: {
        enabled: true,
        label: 'Warehouse Stock / Inventory',
        promptProfile: 'general_asset',
        requiredFields: ['stockDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      goods_in_transit: {
        enabled: true,
        label: 'Goods in Transit / Cargo',
        promptProfile: 'general_asset',
        requiredFields: ['cargoDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      building_materials: {
        enabled: true,
        label: 'Building Materials',
        promptProfile: 'general_asset',
        requiredFields: ['stockDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      scrap: {
        enabled: true,
        label: 'Scrap / Recoverable Parts',
        promptProfile: 'general_asset',
        requiredFields: ['stockDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      agriculture: {
        enabled: true,
        label: 'Agricultural Stock / Equipment',
        promptProfile: 'general_asset',
        requiredFields: ['stockDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      medical_equipment: {
        enabled: true,
        label: 'Medical Equipment',
        promptProfile: 'general_asset',
        requiredFields: ['equipmentDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      energy_equipment: {
        enabled: true,
        label: 'Energy / Oil & Gas Equipment',
        promptProfile: 'machinery',
        requiredFields: ['equipmentDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      aviation_equipment: {
        enabled: true,
        label: 'Aviation / Special Risk Equipment',
        promptProfile: 'machinery',
        requiredFields: ['equipmentDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      other: {
        enabled: true,
        label: 'Other Salvage Asset',
        promptProfile: 'general_asset',
        requiredFields: ['equipmentDescription'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
    },
    insuranceClasses: {
      motor: {
        enabled: true,
        label: 'Motor',
        description: 'Vehicles, motorcycles, fleet assets, and motor salvage.',
        defaultAssetTypes: ['vehicle'],
      },
      goods_in_transit: {
        enabled: true,
        label: 'Goods in Transit',
        description: 'Cargo, stock, consignments, and goods damaged while in transit.',
        defaultAssetTypes: ['goods_in_transit', 'stock', 'building_materials', 'electronics', 'machinery', 'other'],
      },
      fire: {
        enabled: true,
        label: 'Fire and Special Perils',
        description: 'Fire, smoke, water, and peril-related salvage across property or goods.',
        defaultAssetTypes: ['property', 'stock', 'building_materials', 'furniture', 'electronics', 'appliance', 'machinery', 'scrap', 'other'],
      },
      burglary: {
        enabled: true,
        label: 'Burglary/Theft',
        description: 'Recovered, partially recovered, or damaged assets from theft events.',
        defaultAssetTypes: ['electronics', 'jewelry', 'furniture', 'appliance', 'machinery', 'other'],
      },
      marine: {
        enabled: true,
        label: 'Marine Cargo',
        description: 'Marine cargo and port-to-port shipment losses.',
        defaultAssetTypes: ['goods_in_transit', 'stock', 'machinery', 'electronics', 'building_materials', 'other'],
      },
      engineering: {
        enabled: true,
        label: 'Engineering/Plant',
        description: 'Plant, machinery, equipment breakdown, and contractor equipment salvage.',
        defaultAssetTypes: ['machinery'],
      },
      electronics_equipment: {
        enabled: true,
        label: 'Electronics and Equipment',
        description: 'Consumer electronics, office equipment, devices, and appliances.',
        defaultAssetTypes: ['electronics', 'appliance'],
      },
      property_all_risks: {
        enabled: true,
        label: 'Property All Risks',
        description: 'Buildings, fixtures, contents, and general property salvage.',
        defaultAssetTypes: ['property', 'furniture', 'electronics', 'appliance', 'building_materials', 'scrap', 'other'],
      },
      agriculture: {
        enabled: true,
        label: 'Agriculture',
        description: 'Crops, produce, farm inventory, and agricultural equipment.',
        defaultAssetTypes: ['agriculture', 'machinery', 'stock', 'other'],
      },
      oil_and_gas: {
        enabled: false,
        label: 'Oil and Gas',
        description: 'Energy-sector equipment, materials, and specialist salvage.',
        defaultAssetTypes: ['energy_equipment', 'machinery', 'scrap', 'electronics', 'other'],
      },
      aviation: {
        enabled: false,
        label: 'Aviation',
        description: 'Aircraft parts, ground support, and aviation-related salvage.',
        defaultAssetTypes: ['aviation_equipment', 'machinery', 'electronics', 'scrap', 'other'],
      },
      liability: {
        enabled: true,
        label: 'Liability',
        description: 'Third-party property losses where salvage recovery is applicable.',
        defaultAssetTypes: ['vehicle', 'property', 'other'],
      },
      other: {
        enabled: true,
        label: 'Other',
        description: 'Use when the claim class does not fit the configured options.',
        defaultAssetTypes: ['other'],
      },
    },
    voiceNotesEnabled: true,
    claimsAdjusterTranscriptEditable: true,
    salvageManagerTranscriptReviewRequired: true,
  },
  aiValuation: {
    enabled: true,
    providerPriority: ['gemini', 'claude', 'serper'],
    marketSearchEnabled: true,
    repairVsReplaceEnabled: true,
    showDamageCostBreakdownToVendors: false,
    lowConfidenceRequiresManualReview: true,
    minimumOverallConfidence: 70,
    minimumMarketConfidence: 65,
    minimumDamageConfidence: 70,
    minimumMarketSourceCount: 3,
    sourceDiversityRequired: true,
    maxAllowedPriceSpreadPercent: 55,
    reservePriceRatio: 0.7,
    totalLossSalvageCapRatio: 0.3,
    exchangeRates: {
      USD: 1600,
      GBP: 2000,
      EUR: 1700,
    },
    repairCostMultipliers: {
      laborPercent: 18,
      paintAndMaterialsPercent: 12,
      logisticsPercent: 6,
      severeDamageMultiplier: 1.35,
      moderateDamageMultiplier: 1.15,
    },
    pricePlausibility: {
      marketMinimums: {
        vehicle: 500000,
        electronics: 10000,
        appliance: 20000,
        machinery: 100000,
        property: 1000000,
        jewelry: 5000,
        furniture: 10000,
        stock: 1000,
        goods_in_transit: 1000,
        building_materials: 1000,
        scrap: 500,
        agriculture: 1000,
        medical_equipment: 20000,
        energy_equipment: 50000,
        aviation_equipment: 50000,
        equipment: 20000,
        other: 1000,
        general_asset: 1000,
      },
      partMinimums: {
        vehicle: 3000,
        vehicle_body: 5000,
        vehicle_powertrain: 50000,
        machinery: 20000,
        property: 10000,
        electronics: 5000,
        appliance: 5000,
        furniture: 3000,
        medical_equipment: 10000,
        energy_equipment: 20000,
        aviation_equipment: 20000,
        equipment: 10000,
        general_asset: 3000,
      },
      partMaximums: {
        vehicle: 5000000,
        vehicle_body: 4000000,
        vehicle_powertrain: 8000000,
        machinery: 15000000,
        property: 50000000,
        electronics: 2000000,
        appliance: 3000000,
        furniture: 2000000,
        medical_equipment: 50000000,
        energy_equipment: 100000000,
        aviation_equipment: 100000000,
        equipment: 30000000,
        general_asset: 5000000,
      },
    },
    photoRequirements: {
      vehicle: {
        minimumPhotos: 5,
        recommendedPhotos: 8,
        requiredAngles: ['front', 'rear', 'left side', 'right side', 'interior or odometer'],
      },
      machinery: {
        minimumPhotos: 5,
        recommendedPhotos: 8,
        requiredAngles: ['front', 'rear', 'left side', 'right side', 'serial plate or hour meter'],
      },
      property: {
        minimumPhotos: 5,
        recommendedPhotos: 10,
        requiredAngles: ['front exterior', 'rear exterior', 'interior', 'damage close-up', 'site context'],
      },
      electronics: {
        minimumPhotos: 3,
        recommendedPhotos: 5,
        requiredAngles: ['front', 'back', 'damage close-up'],
      },
      general_asset: {
        minimumPhotos: 3,
        recommendedPhotos: 5,
        requiredAngles: ['front', 'back', 'damage close-up'],
      },
    },
  },
  notifications: {
    emailEnabled: true,
    smsEnabled: true,
    pushEnabled: true,
    smsCategories: ['otp', 'auction_won', 'forfeiture', 'grace_period', 'pickup_code'],
    roleFanoutShouldBeQueued: true,
  },
  documents: {
    requiredAuctionDocuments: ['bill_of_sale', 'liability_waiver'],
    attachPaymentReceiptToAuctionDocuments: true,
    useBrandLetterhead: true,
    authorizedSignerName: '',
    authorizedSignerTitle: '',
    authorizedSignatureUrl: '',
    billOfSaleDisclaimerTitle: 'AS-IS, WHERE-IS SALE',
    billOfSaleDisclaimerBody:
      'This asset is sold "AS-IS, WHERE-IS" with NO WARRANTIES, express or implied. Buyer accepts all risks and responsibilities associated with this purchase.',
    liabilityWaiverClauses: [
      {
        title: 'AS-IS CONDITION',
        body: 'I am purchasing the salvage item(s) in "AS-IS, WHERE-IS" condition with ALL FAULTS and NO WARRANTIES, express or implied.',
      },
      {
        title: 'INSPECTION OPPORTUNITY',
        body: 'I have had the opportunity to inspect the item(s) through photos, descriptions, and damage assessment provided by the seller or platform operator.',
      },
      {
        title: 'RELEASE OF LIABILITY',
        body: 'I hereby release, waive, and forever discharge the seller, platform operator, their officers, employees, and agents from any and all liability, claims, demands, or causes of action arising from injuries, property damage, defects, malfunctions, failures, or any misrepresentation or omission regarding the item condition.',
      },
      {
        title: 'ASSUMPTION OF RISK',
        body: 'I understand and accept all risks associated with purchasing and using salvage property, including structural damage not visible in photos, mechanical failures, safety hazards, and environmental contamination.',
      },
      {
        title: 'INDEMNIFICATION',
        body: 'I agree to indemnify and hold harmless the seller and platform operator from any claims by third parties arising from my ownership or use of the salvage item(s).',
      },
      {
        title: 'FINAL SALE',
        body: 'I understand this sale is FINAL and NON-REFUNDABLE.',
      },
      {
        title: 'GOVERNING LAW',
        body: 'This agreement is governed by the laws of Nigeria.',
      },
    ],
  },
  legal: {
    registrationNumber: 'Configured in enterprise setup',
    addressLine1: 'Registered business address',
    addressLine2: 'Nigeria',
    privacyEmail: 'support@salvagebridge.com',
    dpoEmail: 'support@salvagebridge.com',
    legalEmail: 'support@salvagebridge.com',
    legalLastUpdated: 'April 27, 2026',
  },
  fraud: {
    dojahRiskAlertsEnabled: true,
    ipFraudDetectionEnabled: true,
    biddingFraudDetectionEnabled: true,
    highRiskRequiresManualReview: true,
    vendorInactivityAlertsEnabled: true,
    vendorInactivityDays: 60,
    vendorInactivityCooldownDays: 14,
  },
  reports: {
    defaultDateRange: 'all_time',
    excludeMarkedTestDataByDefault: false,
    requireConsistentMetricDefinitions: true,
  },
};
