import type { BusinessPolicy } from './types';

export const CURRENT_NEM_POLICY_VERSION = 'nem-default-2026-05-23';

export const DEFAULT_BUSINESS_POLICY: BusinessPolicy = {
  version: CURRENT_NEM_POLICY_VERSION,
  updatedAt: '2026-05-23T00:00:00.000Z',
  branding: {
    brandName: 'NEM Salvage',
    legalName: 'NEM Insurance Plc',
    supportEmail: 'support@nemsalvage.com',
    primaryColor: '#800020',
    accentColor: '#FFD700',
    logoPath: '/icons/Nem-insurance-Logo.jpg',
    homepageMode: 'landing',
    homepageTemplate: 'salvage_showcase',
    homepageCopy: {
      heroTitle: 'Streamline Salvage Recovery',
      heroSubtitle: '10x faster processing with AI-powered damage assessment',
      supportingText: 'Instant payments - Real-time bidding - Mobile-first platform',
      primaryCtaLabel: 'Start Bidding',
      secondaryCtaLabel: 'Login',
    },
  },
  auth: {
    emailPasswordEnabled: true,
    googleOAuthEnabled: false,
    businessEmailOnly: false,
    allowedEmailDomains: [],
    staffMfaRequired: false,
    vendorMfaRequired: false,
    userManagedMfaAllowed: true,
  },
  onboarding: {
    mode: 'tiered_bvn_fee_tier2',
    tier1BidLimit: 500_000,
    registrationFeeRequired: true,
    registrationFeeAmount: 12_500,
    registrationFeeDueDays: 7,
    allowBrowseBeforeKyc: false,
    allowBidAfterTier1: true,
    requireTier2ForUnlimitedBidding: true,
    finalTier2Decision: 'manual_review',
  },
  kyc: {
    provider: 'dojah',
    tier1RequiresBvn: true,
    tier2RequiresBusinessData: true,
    tier2RequiresGovernmentId: true,
    tier2RequiresLiveness: true,
    tier2RequiresAddress: true,
    tier2RequiresAmlScreening: true,
    tier2RequiresDuplicateIdentityCheck: true,
    providerPassRequiresInternalReview: true,
  },
  payments: {
    defaultProvider: 'paystack',
    registrationFeeProvider: 'paystack',
    auctionPaymentProvider: 'paystack',
    walletEnabled: true,
    paystackEnabled: true,
    flutterwaveEnabled: false,
    hybridPaymentEnabled: true,
    manualPaymentEnabled: false,
    paymentDeadlineAfterSigningHours: 72,
  },
  escrow: {
    depositSystemEnabled: true,
    depositRatePercent: 10,
    minimumDepositFloor: 100_000,
    topBiddersToKeepFrozen: 3,
    forfeiturePercentage: 100,
  },
  auctions: {
    minimumBidIncrement: 20_000,
    documentValidityHours: 48,
    maxGraceExtensions: 2,
    graceExtensionDurationHours: 24,
    fallbackBufferHours: 24,
    reserveValueStrategy: 'percentage_of_salvage_value',
    reserveValuePercentage: 70,
    socketMode: 'polling_primary_socket_secondary',
  },
  cases: {
    enabledAssetTypes: {
      vehicle: {
        enabled: true,
        label: 'Vehicle',
        promptProfile: 'vehicle',
        requiredFields: ['vehicleMake', 'vehicleModel', 'vehicleYear'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      machinery: {
        enabled: true,
        label: 'Machinery & Equipment',
        promptProfile: 'machinery',
        requiredFields: ['machineryBrand', 'machineryType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      property: {
        enabled: true,
        label: 'Property',
        promptProfile: 'property',
        requiredFields: ['propertyType', 'propertyAddress'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      electronics: {
        enabled: true,
        label: 'Electronics',
        promptProfile: 'electronics',
        requiredFields: ['electronicsBrand', 'electronicsModel'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      jewelry: {
        enabled: false,
        label: 'Jewelry & Watches',
        promptProfile: 'jewelry',
        requiredFields: ['jewelryType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      appliance: {
        enabled: false,
        label: 'Appliance',
        promptProfile: 'electronics',
        requiredFields: ['applianceBrand', 'applianceModel'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
      furniture: {
        enabled: false,
        label: 'Furniture',
        promptProfile: 'general_asset',
        requiredFields: ['furnitureType'],
        requiresAiAnalysis: true,
        requiresMarketValue: true,
        requiresInspectionLocation: true,
      },
    },
    voiceNotesEnabled: true,
    claimsAdjusterTranscriptEditable: true,
    salvageManagerTranscriptReviewRequired: true,
  },
  aiValuation: {
    enabled: true,
    providerPriority: ['gemini', 'claude', 'serper'],
    marketSearchEnabled: true,
    repairVsReplaceEnabled: true,
    showDamageCostBreakdownToVendors: false,
    lowConfidenceRequiresManualReview: true,
  },
  notifications: {
    emailEnabled: true,
    smsEnabled: true,
    pushEnabled: true,
    smsCategories: ['otp', 'auction_won', 'forfeiture', 'grace_period', 'pickup_code'],
    roleFanoutShouldBeQueued: true,
  },
  documents: {
    requiredAuctionDocuments: ['bill_of_sale', 'liability_waiver'],
    attachPaymentReceiptToAuctionDocuments: true,
    useBrandLetterhead: true,
  },
  fraud: {
    dojahRiskAlertsEnabled: true,
    ipFraudDetectionEnabled: true,
    biddingFraudDetectionEnabled: true,
    highRiskRequiresManualReview: true,
  },
  reports: {
    defaultDateRange: 'all_time',
    excludeMarkedTestDataByDefault: false,
    requireConsistentMetricDefinitions: true,
  },
};
